### ISSUE TITLE
JEI recipe preview is small

### ISSUE THREAD

**Issue by Goldenlion5648** [Frinn38/Custom-Machinery#1]
This is the preview size in JEI:
![image](https://user-images.githubusercontent.com/32916571/118016435-608cce80-b323-11eb-8656-01e0b527c968.png)

Here is the thermal igneous extruder for comparison:
![image](https://user-images.githubusercontent.com/32916571/118016534-83b77e00-b323-11eb-9e78-52c1bbe0ea2d.png)

**Comment by Frinn38** [comment]
Yeah the JEI integration is still far from perfect. It just takes the machine GUI, remove components that are not needed, shrink it to half it's original size to fit in the recipe GUI and display it that's why it is this small. 
I will improve it in the future, at least to cut all the blank space and scale it properly using that space.
In the meantime I will let this issue open.

**Comment by Frinn38** [comment]
Still not perfect, but better
![](https://media.discordapp.net/attachments/842550366763614261/846758726135447593/unknown.png?width=656&height=670)

I will continue to improve this over time, but for now it should be good
