### ISSUE TITLE
[1.18.2 Fabric] Incompatibility with Chisels and Bits (crash)

### ISSUE THREAD

**Issue by KonSola5** [Frinn38/Custom-Machinery#101]
When adding Custom Machinery to a modpack, the game crashes with:
`[14:32:38] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1309 failed`
upon attempting to load the pack.

Here's the full log:

[latest.log](https://github.com/Frinn38/Custom-Machinery/files/12161192/latest.log)

(I can't find the `debug.log` though...)

**Comment by KonSola5** [comment]
Runs fine on the minimal setup. Strange. This must be some sort of mod incompatibility.

**Comment by KonSola5** [comment]
Turns out, the mod is incompatible with **Chisels and Bits**.

**Comment by Frinn38** [comment]
It seems that both Custom Machinery and Chisels & Bits mixin the same methods, probably to achieve the same goal (modifying light and sound emissions of a block).
Unfortunately that feature that can be easily achieved in Forge seems to be missing on Fabric, which is why both mods are relying on mixins to do it.
I fixed it on my side by making my mixins optionals, that means that in latest update (0.8.6) CM will not crash if C&B is installed, however some feature such as light and sounds appearance properties won't work.

**Comment by Frinn38** [comment]
Should be fixed in CM 0.9.2
