### ISSUE TITLE
Item Requirement NBT broken in v0.8+

### ISSUE THREAD

**Issue by arketec** [Frinn38/Custom-Machinery#103]
Nbt is being ignored in custommachinery:item requirements in all versions 0.8+
It works fine in 0.7.6 from my testing

json files:
[machine](https://pastebin.com/cRLanYPR)

[recipe](https://pastebin.com/MmgdazE7)

**Comment by Frinn38** [comment]
The issue was that I accidentally deleted String nbt support, so basically instead of
```json
"nbt": "{sometag:\"somevalue\"}"
```
you had to do : 
```json
"nbt": {
    "sometag": "somevalue"
}
```
And that json to nbt syntax behave weird sometime so now from CM 0.8.7 I reintroduced String nbt syntax. 
Both syntax are supported but the String one should be preferred.
Sorry for the delay, didn't had much time to work on CM this month.
