### ISSUE TITLE
[Suggestion] Add support for recipes in JEI

### ISSUE THREAD

**Issue by donoya** [Frinn38/Custom-Machinery#14]
I can't seem to get it to show my machine's recipes in JEI. I was able to verify it worked in my machine, but for some reason, it doesn't seem possible at this time to have it make a tab, yet. At least not from a user's end. If this would be possible for you to implement, I'd really appreciate it.

**Comment by Frinn38** [comment]
Well the jei integration should make a tab for each machine and show each recipe in jei...

Some questions : 
1) Does your machine have a gui defined ? The jei recipe gui will be pade based on the machine gui so if you don't specify any gui elements in the machine json nothing will show in the jei recipe gui.
2) Are there any errors in your log ? If there is an error while trying to load/show a recipe jei will not show it. Please send your debug.log here.
3) How do you create your recipe/machine ? I tested the jei integration only with datapacks so there may be some bugs with CT/kubejs compat of you're using them.

The jei integration is far from perfect and can(will) contains bugs due to my limited time I can't test every possibility to see if it's works fine, that's why this mod is in beta.
But I try to fix every bug that is reported as soon as possible, to do this I need a maximum of informations on the bug so that's why I asked your logs.

**Comment by donoya** [comment]
I think I figured it out. Doing /reload in the console doesn't seem to register the JEI tab. I had trouble at first because I forgot to change a few things when copying from the example, so when I loaded the game, the machine didn't work and neither did the recipe. Then, after fixing it and doing /reload, the machine worked, but the tab did not. It would still be nice to have a feature where doing /reload would show the JEI tab, so I'll leave this issue up for now. If you can't implement it or don't think it's necessary, feel free to close this issue.

**Comment by Frinn38** [comment]
Digged a bit in the jei code, basically when a jei plugin (a mod that add jei support) make an error because of a wrong recipe or something like that, jei disable the plugin and the only way to re-enable it is to reboot the game.
The way to fix that is obviously to not error jei, in the last update (0.3.5) I added some checks that will just log the error instead of making jei disable the plugin. This way the user should be able to find the error in the log, fix it and a /reload will show the recipe fine.
That said it may have some place that still error jei in some specific cases. If that happen feel free to re-open this issue and post the jei error (or full debug.log file if you don't find the error).
