### ISSUE TITLE
Create integration

### ISSUE THREAD

**Issue by rlnt** [Frinn38/Custom-Machinery#15]
Hey there. Awesome mod!
A feature which would be really nice is Create integration. Being able to use kinetic energy to craft specific recipes would be awesome.
Power your custom machine with a water wheel for example.

**Comment by Frinn38** [comment]
Various mods integration, such as create rotation, mek gas, astral starlight and a lot other are planned.
But all of these are a very low priority as I want to first implement all the basic features and fix all current issues.
Basically, I will not start making an integration for other mods systems until the mod is in stable state.
Note that when making this mod I try to make it addon friendly (as much as I can, the doc is still lacking). So if anyone want to make an addon to support any other mod system it should be possible, otherwise I will make them myself when the base mod will be stable enough.

**Comment by Frinn38** [comment]
Also the full planned features/to-do list is shown and updated on the discord. Feel free to take a look and suggest anything you think would be useful and is not yet on the list.
