### ISSUE TITLE
How do you use shaders with this mod?

### ISSUE THREAD

**Issue by Griffork** [Frinn38/Custom-Machinery#36]
I'm using optifine and the two different shaders I've tried have resulted in the blocks for this mod being completely invisible. How can I get this mod to work with shaders?

I have tried Complementary Shaders with compatibility mode set to on and AstraLex shaders.
https://shadersmods.com/complementary-shaders/
https://shadersmods.com/astralex-shaders/

**Comment by Frinn38** [comment]
Optifine remove some part of the MC/Forge code to "improve fps", Custom Machinery probably use one of the features removed by OF.
It's impossible to debug as OF is closed source and can't be loaded in a dev workspace, so basically I can't do anything.
At least it doesn't crash, that's a good improvement since last time I used OF.

**Comment by lorenzocorallo** [comment]
@Griffork have you found a solution?
