### ISSUE TITLE
The value cannot exceed 9 digits. Is there any way to raise this upper limit

### ISSUE THREAD

**Issue by StarZeroRI** [Frinn38/Custom-Machinery#41]
The value cannot exceed 9 digits. Is there any way to raise this upper limit. 
Or support higher values, which will directly become negative after exceeding

**Comment by StarZeroRI** [comment]
![image](https://user-images.githubusercontent.com/89684932/164489491-bad89a47-05a5-401f-b6eb-30cddba8f1e8.png)

**Comment by Frinn38** [comment]
The exact max value is 2 147 483 647.
That's a Forge Energy system limitation, thought this limit could be extended with some work.
I add that to my to-do list.

**Comment by StarZeroRI** [comment]
Thanks, looking forward to it very much! This mod is fantastic!

**Comment by Frinn38** [comment]
Just added this feature, was easier than expected. 
The new max capacity of the energy component is now 9,223,372,036,854,775,807 (equivalent of a T8 draconic energy core, good luck to fill that ^^).
However the max input and output are still the same (2 147 483 647), it's the maximum amount of FE that can be transfered using the Forge Energy API so I can't do much about that.
Also, now if you specify a value higher than the limit for the energy component capacity, the component won't be added and an error will be logged (instead of adding the component with a negative capacity).
These additions will be included in the next update.

**Comment by Frinn38** [comment]
Added in 0.5.8
