### ISSUE TITLE
[1.16.5] Problem with upgrade

### ISSUE THREAD

**Issue by Z4RM** [Frinn38/Custom-Machinery#56]
Hello,

I have created upgrades but if I set for example the 'custommachinery:speed' at 2, the machine go 2 times more slow. So I have set this to 0.5, but the tooltip write "-50% speed". Is there a way to fix this, or hide the tooltip and I put mine ? Thank you by advance.

Cordially,
Z4RM

**Comment by Frinn38** [comment]
I will look to fix that soon

**Comment by Frinn38** [comment]
Fixed in 1.18, also added a way to tweak the modifier tooltip.
Sorry for 1.16 but I can't support both versions at the same time.

EDIT : Pushed a new version that change the speed upgrade tooltip
from `-50% Speed` to `-50% Recipe duration`
That's far from perfect but at least its description is not inverted anymore.
