### ISSUE TITLE
Ghost item rendering improperly in JEI

### ISSUE THREAD

**Issue by Nevrai** [Frinn38/Custom-Machinery#72]
This issue does not happen in my other custom machine, nor does it happen in this particular machine itself. It only happens when viewing its recipes in JEI. I’m not sure what is causing this, whether it’s the number of slots or the size of the background. I’m assuming it’s the number of slots, but this does not happen with the other machine as mentioned, and that one goes off the edges of JEI’s GUI even further.

![WC7WAMi](https://user-images.githubusercontent.com/59761487/194777974-e2d0d3c6-c634-4104-bd6a-c288043a8a27.png)

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest)
* **Custom Machinery:** 0.6.7 (latest)

**Comment by Frinn38** [comment]
Can you send the machine json that have this gui.

**Comment by Nevrai** [comment]
Here is the JSON file: https://pastebin.com/VhLc39jg

And here’s the texture used for the background:
![optimum_workbench_background](https://user-images.githubusercontent.com/59761487/194961705-c22a969e-05d7-4ccd-b74b-57eaf05b0f1a.png)

**Comment by Frinn38** [comment]
Don't set gui elements `x` and `y` properties to negative values, even if it may work in the machine gui, I believe that's why the element try to render out of the jei recipe screen.
If you need more space than the default 256*192 gui size use the size gui element to change it : 
```json
{
    "type": "custommachinery:size",
    "width": 290,
    "height": 295
}
```
See more [here](https://frinn.gitbook.io/custom-machinery-1.18/creating-custom-machines/machine-gui/size-element)
